##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: tallergrupo7
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:
    
url:
  balances: https://shy-smoke-9103.getsandbox.com/v1/operations/product-specific/deposits/accounts/balances
  movements: https://purple-wave-7604.getsandbox.com/deposit/movements
