##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: tallergrupo7
  devtools:
    add-properties: false
  profiles:
    include:
    
url:
  balances: https://bitter-thunder-813.getsandbox.com/v1/operations/product-specific/deposits/accounts/balances
  movements: https://late-dust-2436.getsandbox.com/deposit/movements
