##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: tallergrupo7
  devtools:
    add-properties: false
  profiles:
    include:

balances:
  url: https://patient-river-5918.getsandbox.com/v1/operations/product-specific/deposits/accounts/balances
  timeout: 5
movements:
  url: https://young-breeze-416.getsandbox.com/deposit/movements
  timeout: 5
